# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.
auth_enabled: false
limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_global_streams_per_user: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
    replication_factor: 1
    heartbeat_period: 5s
    heartbeat_timeout: 10s
  path_prefix: /tmp/loki
schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h
storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    cache_ttl: 24h
  filesystem:
    directory: /tmp/loki/chunks
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    join_after: 0s
    min_ready_duration: 0s
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
pattern_ingester:
  enabled: true