scrape_configs:
- job_name: 'prometheus_test'
  scrape_interval: 5s
  static_configs:
    - targets: ['docker.host.internal:9090']

- job_name: 'planning_poker_app'
  scrape_interval: 5s
  static_configs:
    - targets: ['localhost:4000']
